"""migration

Revision ID: 1d5c9d395541
Revises: 7e091371539c
Create Date: 2025-04-27 18:49:32.309359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d5c9d395541'
down_revision = '7e091371539c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('IsActive', sa.Boolean(), nullable=False))
        batch_op.drop_column('IsApproved')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('IsApproved', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.drop_column('IsActive')

    # ### end Alembic commands ###
