"""Initial migratio

Revision ID: 210f748d3b9e
Revises: 
Create Date: 2025-04-27 15:02:25.377979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '210f748d3b9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('UserID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NickName', sa.String(length=40), nullable=False),
    sa.Column('UserName', sa.String(length=40), nullable=False),
    sa.Column('LastName', sa.String(length=40), nullable=False),
    sa.Column('Email', sa.String(length=120), nullable=False),
    sa.Column('PasswordHash', sa.String(length=70), nullable=False),
    sa.Column('IsApproved', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('NickName')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
