"""migration

Revision ID: 2efadc238562
Revises: f91073246277
Create Date: 2025-04-28 12:12:30.942715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2efadc238562'
down_revision = 'f91073246277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UsersId', sa.Integer(), nullable=False),
    sa.Column('FriendsId', sa.Integer(), nullable=False),
    sa.Column('Status', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['FriendsId'], ['users.UserID'], ),
    sa.ForeignKeyConstraint(['UsersId'], ['users.UserID'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    # ### end Alembic commands ###
