"""migration

Revision ID: 7e091371539c
Revises: 210f748d3b9e
Create Date: 2025-04-27 18:48:26.128819

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e091371539c'
down_revision = '210f748d3b9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('WinCount', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('MatchCount', sa.Integer(), nullable=False))
        batch_op.alter_column('PasswordHash',
               existing_type=mysql.VARCHAR(length=70),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('PasswordHash',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=70),
               existing_nullable=False)
        batch_op.drop_column('MatchCount')
        batch_op.drop_column('WinCount')

    # ### end Alembic commands ###
