"""migration

Revision ID: f91073246277
Revises: 1d5c9d395541
Create Date: 2025-04-28 00:55:14.128779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f91073246277'
down_revision = '1d5c9d395541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levels',
    sa.Column('LevelsId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UsersId', sa.Integer(), nullable=False),
    sa.Column('NickName', sa.String(length=40), nullable=False),
    sa.Column('Level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['UsersId'], ['users.UserID'], ),
    sa.PrimaryKeyConstraint('LevelsId'),
    sa.UniqueConstraint('NickName')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('levels')
    # ### end Alembic commands ###
